filter:
    excluded_paths:
        - "tests/*"
        - ".atoum.php"
        - "src/Resources/public/js/bootsrap.min.js"
        - "src/Resources/public/js/jquery.min.js"
        - "src/Resources/public/js/run_prettify.js"
    dependency_paths:
        - "env/*"
        - "vendor/*"

before_commands:
    - "composer install"

tools:
    external_code_coverage:
        timeout: 600
    php_mess_detector: true
    php_code_sniffer: true
    sensiolabs_security_checker: true
    php_pdepend: true
    php_loc: true
    php_cpd: false
